### ISSUE TITLE
Edge case of zero edit count

### ISSUE THREAD

**Issue by howardxu520** [YeoLab/MARINE#45]
When no edit is found, I encountered this error. It seems to be an edge case that marine should capture and return empty file.

```
0it [00:00, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/tscc/projects/ps-yeolab4/software/marine/1.0.10a/bin/MARINE/marine.py", line 688, in <module>
    run(bam_filepath, 
  File "/tscc/projects/ps-yeolab4/software/marine/1.0.10a/bin/MARINE/marine.py", line 339, in run
    overall_label_to_list_of_contents, results, total_seconds_for_reads_df, total_reads_processed, counts_summary_df = edit_finder(
  File "/tscc/projects/ps-yeolab4/software/marine/1.0.10a/bin/MARINE/marine.py", line 58, in edit_finder
    total_seconds_for_reads, counts_summary_df = run_edit_identifier(
  File "/tscc/projects/ps-yeolab4/software/marine/1.0.10a/bin/MARINE/src/core.py", line 74, in run_edit_identifier
    all_counts_summary_dfs_combined = pd.concat(all_counts_summary_dfs, axis=1)
  File "/tscc/projects/ps-yeolab4/software/miniconda_tscc2/envs/marine-1.0.10a/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 372, in concat
    op = _Concatenator(
  File "/tscc/projects/ps-yeolab4/software/miniconda_tscc2/envs/marine-1.0.10a/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 429, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

**Comment by ekofman** [comment]
Addressed with PR and new test: https://github.com/YeoLab/MARINE/pull/60
